apiVersion: v1
kind: Service
metadata:
  name: apm-server
  namespace: nodejs-app
spec:
  selector:
    app: apm-server
  ports:
    - protocol: TCP
      port: 8200
      targetPort: 8200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apm-server
  namespace: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apm-server
  template:
    metadata:
      labels:
        app: apm-server
    spec:
      containers:
        - name: apm-server
          image: docker.elastic.co/apm/apm-server:7.17.1
          ports:
            - containerPort: 8200
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
            requests:
              memory: "512Mi"
              cpu: "250m"
          env:
            - name: OUTPUT_ELASTICSEARCH_ENABLED
              value: "true"
            - name: OUTPUT_ELASTICSEARCH_HOSTS
              value: "[\"http://elasticsearch:9200\"]"
            - name: SETUP_KIBANA_HOST
              value: "http://kibana:5601"
