version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.1
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - elastic
    depends_on:
      - elasticsearch

  apm-server:
    image: docker.elastic.co/apm/apm-server:7.17.1
    ports:
      - "8200:8200"
    networks:
      - elastic
    depends_on:
      - elasticsearch
    environment:
      OUTPUT_ELASTICSEARCH_ENABLED: "true"
      OUTPUT_ELASTICSEARCH_HOSTS: '[ "elasticsearch:9200" ]'
      SETUP_KIBANA_HOST: "http://kibana:5601"

networks:
  elastic:
    driver: bridge
