apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  namespace: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - name: my-node-microservice
        image: ilyas0v/my-node-microservice:16
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
        env:
        - name: SERVICE_TYPE
          value: "service-a"
        envFrom:
        - configMapRef:
            name: env-config
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: service-a
  namespace: nodejs-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: service-a
